FROM laiyijie/es_with_plugin:20180608_104043 
	
COPY --chown=elasticsearch:elasticsearch elasticsearch.yml /usr/share/elasticsearch/config/
#COPY --chown=elasticsearch:elasticsearch jvm.options /usr/share/elasticsearch/config/

